name: searcher_installer_go
description: 'Installer/Updater for Searcher: Houdini addon.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  google_fonts: ^1.1.0
  flutter_hooks: ^0.9.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  # -- Data ------------------------
  logger: ^0.9.1
  global_configuration: ^1.5.0
  provider:
  dynamic_widget: ^2.0.2
  expansion_tile_card: ^1.0.3
  expandable: ^4.1.4
  #  basic_utils: ^2.5.3
  #  injectable: ^0.4.0+1

  # --- Helper fucnctions -----------
  uuid:
  event: ^1.1.4
  eventsubscriber: ^1.2.0
  stack_trace:
  event_bus: ^1.1.1
  flutter_markdown: ^0.4.1
  supercharged: ^1.6.0
  cross_local_storage: ^1.1.1
  guard: ^1.0.4
  shared_preferences: ^0.5.7+3
  localstorage: ^3.0.2+5
  path_provider: ^1.6.10
  sa_v1_migration: ^1.1.2
  intl: ^0.16.1
  file_picker: ^1.10.0
  url_launcher: ^5.4.10
  url_launcher_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
  draggable_scrollbar: ^0.0.4
  get_it: ^4.0.2

  # -- Visual -----------------------
  transparent_image: ^1.0.0
  list_tile_more_customizable: ^1.3.0
  #  cupertino_icons: ^0.1.3
  #  expansion_card: ^0.1.0
  #  icon_shadow: ^1.0.1

  # -- UI ---------------------------
  flushbar: ^1.10.4
  fluid_layout: ^0.1.0
  sized_context: ^0.2.1+1
  getflutter: ^1.0.11
  font_awesome_flutter: ^8.8.1
  flutter_icons: ^1.1.0
  quiver:
  transformer_page_view: ^0.1.6
  dynamic_properties: ^1.0.0
  #  flutter_form_builder: ^3.10.1

  # -- Animations -------------------
  simple_animations: ^2.2.1
  sa_anicoto: ^1.0.2
  #  animations: ^1.1.0

  # --- Imports ---------------------
  #  faui:
  #    path: E:/Github/flutter-auth-ui
  firedart: ^0.8.0+1
#    path: E:/Github/firedart


dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  dependency_validator: ^1.5.0
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
#  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/main0.png
    - assets/images/searcher0.png
    - assets/images/searcher2.png
    - assets/images/badge_instance.png
    - google_fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700